name: setup xmake
  # You may pin to the exact commit or the version.
  # uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a
  uses: xmake-io/github-action-setup-xmake@v1
